# Generated by Django 4.2.7 on 2026-02-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_1", models.CharField(max_length=20, verbose_name="Телефон 1")),
                (
                    "phone_2",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Телефон 2"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("address_ru", models.TextField(verbose_name="Адрес (рус)")),
                (
                    "address_en",
                    models.TextField(blank=True, verbose_name="Адрес (англ)"),
                ),
                ("telegram", models.URLField(blank=True, verbose_name="Telegram")),
                ("whatsapp", models.URLField(blank=True, verbose_name="WhatsApp")),
                ("instagram", models.URLField(blank=True, verbose_name="Instagram")),
                ("facebook", models.URLField(blank=True, verbose_name="Facebook")),
                ("youtube", models.URLField(blank=True, verbose_name="YouTube")),
                (
                    "work_hours_ru",
                    models.CharField(max_length=255, verbose_name="Часы работы (рус)"),
                ),
                (
                    "work_hours_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Часы работы (англ)"
                    ),
                ),
                (
                    "legal_info_ru",
                    models.TextField(
                        blank=True, verbose_name="Юридическая информация (рус)"
                    ),
                ),
                (
                    "legal_info_en",
                    models.TextField(
                        blank=True, verbose_name="Юридическая информация (англ)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "контакт",
                "verbose_name_plural": "контакты",
            },
        ),
    ]
