# Generated by Django 4.2.7 on 2026-04-28 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_feedback"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="user_id",
        ),
    ]
