# Generated by Django 4.2.7 on 2026-04-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0003_remove_feedback_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="name",
            field=models.TextField(default=123123, max_length=124, verbose_name="Имя"),
            preserve_default=False,
        ),
    ]
