# Generated by Django 4.2.7 on 2026-02-21 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Favourite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="позиция"),
                ),
                (
                    "on_moodboard",
                    models.BooleanField(default=True, verbose_name="в мудборде"),
                ),
                (
                    "moodboard_position",
                    models.PositiveIntegerField(
                        default=0, verbose_name="позиция в мудборде"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favourited_by",
                        to="catalog.item",
                        verbose_name="товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "избранное",
                "verbose_name_plural": "избранное",
                "ordering": ["position"],
            },
        ),
    ]
