# Generated by Django 4.2.7 on 2026-02-21 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("favourites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="favourite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favourites",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
        migrations.AddIndex(
            model_name="favourite",
            index=models.Index(
                fields=["user", "on_moodboard"], name="favourites__user_id_89be32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="favourite",
            index=models.Index(
                fields=["user", "position"], name="favourites__user_id_4b43d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="favourite",
            index=models.Index(
                fields=["user", "moodboard_position"],
                name="favourites__user_id_699b83_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favourite",
            unique_together={("user", "item")},
        ),
    ]
