# Generated by Django 4.2.7 on 2026-02-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArticleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="blog/images/", verbose_name="Изображение"
                    ),
                ),
                (
                    "caption_ru",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Подпись (рус)"
                    ),
                ),
                (
                    "caption_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Подпись (англ)"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "изображение статьи",
                "verbose_name_plural": "изображения статей",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата публикации"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=500, verbose_name="Заголовок (рус)"),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Заголовок (англ)"
                    ),
                ),
                (
                    "short_description_ru",
                    models.TextField(blank=True, verbose_name="Краткое описание (рус)"),
                ),
                (
                    "short_description_en",
                    models.TextField(
                        blank=True, verbose_name="Краткое описание (англ)"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(blank=True, verbose_name="Содержание (рус)"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Содержание (англ)"),
                ),
                (
                    "preview_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog/previews/",
                        verbose_name="Превью",
                    ),
                ),
                (
                    "preview_wide_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog/previews/wide/",
                        verbose_name="Широкое превью",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Опубликовано"),
                ),
                (
                    "is_main",
                    models.BooleanField(default=False, verbose_name="Главный пост"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=1, verbose_name="Порядок"),
                ),
                (
                    "photos",
                    models.ManyToManyField(
                        blank=True, related_name="articles", to="blog.articleimage"
                    ),
                ),
            ],
            options={
                "verbose_name": "статья",
                "verbose_name_plural": "статьи",
                "ordering": ["sort_order", "-published_at", "-created_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="blog_articl_slug_cc8df7_idx"),
                    models.Index(
                        fields=["is_published", "published_at"],
                        name="blog_articl_is_publ_fb6b4d_idx",
                    ),
                    models.Index(
                        fields=["is_main"], name="blog_articl_is_main_50ba61_idx"
                    ),
                    models.Index(
                        fields=["sort_order"], name="blog_articl_sort_or_61ec20_idx"
                    ),
                ],
            },
        ),
    ]
