# Generated by Django 4.2.7 on 2026-02-24 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="photos",
        ),
        migrations.AddField(
            model_name="articleimage",
            name="article",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="blog.article",
                verbose_name="статья",
            ),
            preserve_default=False,
        ),
    ]
