# Generated by Django 4.2.7 on 2026-02-21 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name_ru", models.CharField(max_length=255, verbose_name="имя (рус)")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="имя (англ)"
                    ),
                ),
                (
                    "bio_ru",
                    models.TextField(blank=True, verbose_name="биография (рус)"),
                ),
                (
                    "bio_en",
                    models.TextField(blank=True, verbose_name="биография (англ)"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="slug"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="authors/",
                        verbose_name="фотография",
                    ),
                ),
            ],
            options={
                "verbose_name": "автор",
                "verbose_name_plural": "авторы",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name_ru",
                    models.CharField(max_length=255, verbose_name="название (рус)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="название (англ)"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(blank=True, verbose_name="описание (рус)"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="описание (англ)"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="slug"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активна"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="catalog.category",
                        verbose_name="родительская категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
                "ordering": ["sort_order", "name_ru"],
            },
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name_ru",
                    models.CharField(max_length=255, verbose_name="название (рус)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="название (англ)"
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="значение"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("percent", "процент"), ("fixed", "фиксированная")],
                        default="percent",
                        max_length=10,
                        verbose_name="тип",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="действует с"
                    ),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="действует до"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активна"),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="discounts",
                        to="catalog.category",
                        verbose_name="категории",
                    ),
                ),
            ],
            options={
                "verbose_name": "скидка",
                "verbose_name_plural": "скидки",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name_ru",
                    models.CharField(max_length=500, verbose_name="название (рус)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="название (англ)"
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="артикул",
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(blank=True, verbose_name="описание (рус)"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="описание (англ)"),
                ),
                (
                    "is_art",
                    models.BooleanField(
                        default=False, verbose_name="Является ли АРТом"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="slug"),
                ),
                (
                    "base_price_rub",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Цена для базового размера (коэффициент 1.0)",
                        max_digits=10,
                        verbose_name="базовая цена (руб)",
                    ),
                ),
                (
                    "base_price_usd",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Цена для базового размера (коэффициент 1.0)",
                        max_digits=10,
                        verbose_name="базовая цена (USD)",
                    ),
                ),
                (
                    "is_price_hidden",
                    models.BooleanField(default=False, verbose_name="скрыть цену"),
                ),
                (
                    "image_2d",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="items/2d/",
                        verbose_name="2D-чертёж",
                    ),
                ),
                (
                    "image_3d",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="items/3d/",
                        verbose_name="3D-модель",
                    ),
                ),
                (
                    "preview_photos",
                    models.JSONField(blank=True, default=list, verbose_name="превью"),
                ),
                (
                    "photos",
                    models.JSONField(
                        blank=True, default=list, verbose_name="фотографии"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="активен"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="порядок"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_stock", "В наличии"),
                            ("custom", "Срок изготовления 2 месяца"),
                        ],
                        default="in_stock",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.author",
                        verbose_name="автор",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="catalog.category",
                        verbose_name="категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
                "ordering": ["sort_order", "name_ru"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name_ru",
                    models.CharField(max_length=500, verbose_name="название (рус)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="название (англ)"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(blank=True, verbose_name="описание (рус)"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="описание (англ)"),
                ),
                (
                    "short_description_ru",
                    models.TextField(blank=True, verbose_name="Краткое описание (рус)"),
                ),
                (
                    "short_description_en",
                    models.TextField(
                        blank=True, verbose_name="Краткое описание (англ)"
                    ),
                ),
                (
                    "preview_photos",
                    models.JSONField(blank=True, default=list, verbose_name="превью"),
                ),
                (
                    "photos",
                    models.JSONField(
                        blank=True, default=list, verbose_name="фотографии"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="slug"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="порядок"),
                ),
                (
                    "price_rub",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="цена (руб)",
                    ),
                ),
                (
                    "price_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="цена (USD)",
                    ),
                ),
                (
                    "is_price_hidden",
                    models.BooleanField(default=True, verbose_name="скрыть цену"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="активна"
                    ),
                ),
                (
                    "discounts",
                    models.ManyToManyField(
                        blank=True, related_name="services", to="catalog.discount"
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
                "ordering": ["sort_order", "name_ru"],
            },
        ),
        migrations.CreateModel(
            name="SpecCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name_ru",
                    models.CharField(max_length=255, verbose_name="название (рус)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="название (англ)"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="порядок"),
                ),
            ],
            options={
                "verbose_name": "категория характеристик",
                "verbose_name_plural": "категории характеристик",
                "ordering": ["sort_order", "name_ru"],
            },
        ),
        migrations.CreateModel(
            name="Spec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name_ru",
                    models.CharField(max_length=255, verbose_name="название (рус)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="название (англ)"
                    ),
                ),
                (
                    "value_ru",
                    models.CharField(max_length=255, verbose_name="значение (рус)"),
                ),
                (
                    "value_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="значение (англ)"
                    ),
                ),
                (
                    "price_modifier_rub",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="изменение цены (руб)",
                    ),
                ),
                (
                    "price_modifier_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="изменение цены (USD)",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="specs/",
                        verbose_name="изображение",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="порядок"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specs",
                        to="catalog.speccategory",
                        verbose_name="категория",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specs",
                        to="catalog.item",
                        verbose_name="товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "характеристика",
                "verbose_name_plural": "характеристики",
                "ordering": ["sort_order", "name_ru"],
            },
        ),
        migrations.CreateModel(
            name="ServicePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        upload_to="services/photos/", verbose_name="изображение"
                    ),
                ),
                (
                    "caption_ru",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="подпись (рус)"
                    ),
                ),
                (
                    "caption_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="подпись (англ)"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="порядок"),
                ),
                (
                    "is_preview",
                    models.BooleanField(default=False, verbose_name="превью"),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_objects",
                        to="catalog.service",
                        verbose_name="услуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "фотография услуги",
                "verbose_name_plural": "фотографии услуг",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ItemPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        upload_to="items/photos/", verbose_name="изображение"
                    ),
                ),
                (
                    "caption_ru",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="подпись (рус)"
                    ),
                ),
                (
                    "caption_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="подпись (англ)"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="порядок"),
                ),
                (
                    "is_preview",
                    models.BooleanField(default=False, verbose_name="превью"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_objects",
                        to="catalog.item",
                        verbose_name="товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "фотография",
                "verbose_name_plural": "фотографии",
                "ordering": ["sort_order"],
            },
        ),
        migrations.AddField(
            model_name="discount",
            name="items",
            field=models.ManyToManyField(
                blank=True,
                related_name="discounts",
                to="catalog.item",
                verbose_name="товары",
            ),
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "value_ru",
                    models.CharField(max_length=50, verbose_name="значение (рус)"),
                ),
                (
                    "value_en",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="значение (англ)"
                    ),
                ),
                (
                    "price_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=5,
                        verbose_name="коэффициент цены",
                    ),
                ),
                (
                    "override_price_rub",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="фикс. цена (руб)",
                    ),
                ),
                (
                    "override_price_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="фикс. цена (USD)",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="доступен"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="порядок"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizes",
                        to="catalog.item",
                        verbose_name="товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "размер",
                "verbose_name_plural": "размеры",
                "ordering": ["sort_order", "value_ru"],
                "unique_together": {("item", "value_ru")},
            },
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["slug"], name="catalog_ite_slug_c54288_idx"),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["created_at"], name="catalog_ite_created_46a2dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["sku"], name="catalog_ite_sku_0b70c9_idx"),
        ),
    ]
