# Generated by Django 4.2.7 on 2026-03-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="art_description_en",
            field=models.TextField(
                blank=True,
                help_text="Заполняется только если товар является АРТом",
                verbose_name="описание АРТа (англ)",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="art_description_ru",
            field=models.TextField(
                blank=True,
                help_text="Заполняется только если товар является АРТом",
                verbose_name="описание АРТа (рус)",
            ),
        ),
    ]
