# Generated by Django 4.2.7 on 2026-03-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003__add_root_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="spec",
            name="is_custom",
            field=models.BooleanField(
                default=False,
                help_text="Цена рассчитывается менеджером индивидуально",
                verbose_name="кастомный вариант",
            ),
        ),
    ]
