# Generated by Django 4.2.7 on 2026-03-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_spec_is_custom"),
    ]

    operations = [
        migrations.AddField(
            model_name="size",
            name="is_custom",
            field=models.BooleanField(
                default=False,
                help_text="Цена рассчитывается менеджером индивидуально",
                verbose_name="кастомный размер",
            ),
        ),
    ]
