# Generated by Django 4.2.7 on 2026-03-22 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_size_is_custom"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="availability",
            field=models.CharField(
                choices=[
                    ("in_stock", "В наличии"),
                    ("preorder", "Под заказ"),
                    ("custom", "Срок изготовления 2 месяца"),
                    ("out_of_stock", "Нет в наличии"),
                ],
                db_index=True,
                default="in_stock",
                max_length=20,
                verbose_name="наличие",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="creation_year",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Год создания (только для АРТ)",
                null=True,
                verbose_name="год создания",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="lead_time_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Заполняется если availability = 'custom' или 'preorder'",
                null=True,
                verbose_name="срок изготовления (дни)",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="material",
            field=models.CharField(
                blank=True,
                help_text="Материал (только для АРТ)",
                max_length=255,
                verbose_name="материал",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="technique",
            field=models.CharField(
                blank=True,
                help_text="Техника исполнения (только для АРТ)",
                max_length=255,
                verbose_name="техника",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Вес в килограммах (только для АРТ)",
                max_digits=10,
                null=True,
                verbose_name="вес (кг)",
            ),
        ),
        migrations.CreateModel(
            name="SpecPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        upload_to="spec_photos/", verbose_name="изображение"
                    ),
                ),
                (
                    "caption_ru",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="подпись (рус)"
                    ),
                ),
                (
                    "caption_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="подпись (англ)"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="порядок"),
                ),
                (
                    "spec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="catalog.spec",
                        verbose_name="характеристика",
                    ),
                ),
            ],
            options={
                "verbose_name": "фото характеристики",
                "verbose_name_plural": "фото характеристик",
                "ordering": ["sort_order"],
            },
        ),
    ]
