# Generated by Django 4.2.7 on 2026-05-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_item_availability_item_creation_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="art_size",
            field=models.CharField(
                blank=True,
                help_text="Размер арта (только для АРТ)",
                max_length=255,
                null=True,
                verbose_name="размер арта",
            ),
        ),
    ]
