# Generated by Django 4.2.7 on 2026-02-21 14:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "корзина",
                "verbose_name_plural": "корзины",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="количество",
                    ),
                ),
                (
                    "selected_spec_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="выбранные характеристики",
                    ),
                ),
                (
                    "spec_hash",
                    models.CharField(
                        blank=True, db_index=True, editable=False, max_length=64
                    ),
                ),
                (
                    "cached_price_rub",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=10,
                        verbose_name="кэш цены (руб)",
                    ),
                ),
                (
                    "cached_price_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=10,
                        verbose_name="кэш цены (USD)",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="добавлен"),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cart.cart",
                        verbose_name="корзина",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="catalog.item",
                        verbose_name="товар",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalog.size",
                        verbose_name="размер",
                    ),
                ),
            ],
            options={
                "verbose_name": "товар в корзине",
                "verbose_name_plural": "товары в корзине",
                "ordering": ["-added_at"],
            },
        ),
    ]
