# Generated by Django 4.2.7 on 2026-02-21 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Дом, Работа, Дача",
                        max_length=50,
                        verbose_name="метка",
                    ),
                ),
                ("address", models.TextField(verbose_name="адрес")),
                (
                    "entrance",
                    models.CharField(blank=True, max_length=10, verbose_name="подъезд"),
                ),
                (
                    "floor",
                    models.CharField(blank=True, max_length=10, verbose_name="этаж"),
                ),
                (
                    "apartment",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="квартира/офис"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="комментарий")),
                (
                    "has_elevator",
                    models.BooleanField(default=True, verbose_name="есть лифт"),
                ),
                (
                    "requires_assemblers",
                    models.BooleanField(default=False, verbose_name="нужны сборщики"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="адрес по умолчанию"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создан"),
                ),
            ],
            options={
                "verbose_name": "адрес доставки",
                "verbose_name_plural": "адреса доставки",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="номер заказа",
                    ),
                ),
                (
                    "delivery_address_text",
                    models.TextField(blank=True, verbose_name="адрес (текст)"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                ("phone", models.CharField(max_length=20, verbose_name="телефон")),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="полное имя"),
                ),
                (
                    "delivery_instructions",
                    models.TextField(blank=True, verbose_name="инструкции для курьера"),
                ),
                (
                    "delivery_cost_rub",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="стоимость доставки (руб)",
                    ),
                ),
                (
                    "delivery_cost_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="стоимость доставки (USD)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новый"),
                            ("confirmed", "Подтверждён"),
                            ("paid", "Оплачен"),
                            ("assembling", "В сборке"),
                            ("shipped", "Отправлен"),
                            ("delivered", "Доставлен"),
                            ("cancelled", "Отменён"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                        verbose_name="статус",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("paid", "Оплачен"),
                            ("failed", "Ошибка"),
                            ("refunded", "Возврат"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="статус оплаты",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="способ оплаты"
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ID платежа"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="оплачен"),
                ),
                (
                    "subtotal_rub",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="сумма товаров (руб)",
                    ),
                ),
                (
                    "subtotal_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="сумма товаров (USD)",
                    ),
                ),
                (
                    "discount_rub",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="скидка (руб)",
                    ),
                ),
                (
                    "discount_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="скидка (USD)",
                    ),
                ),
                (
                    "total_rub",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="итого (руб)",
                    ),
                ),
                (
                    "total_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="итого (USD)",
                    ),
                ),
                (
                    "promo_code_text",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="промокод (текст)"
                    ),
                ),
                (
                    "promo_discount_rub",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="скидка промо (руб)",
                    ),
                ),
                (
                    "promo_discount_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="скидка промо (USD)",
                    ),
                ),
                (
                    "customer_comment",
                    models.TextField(blank=True, verbose_name="комментарий клиента"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлён"),
                ),
                (
                    "delivery_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="orders.deliveryaddress",
                        verbose_name="адрес доставки",
                    ),
                ),
            ],
            options={
                "verbose_name": "заказ",
                "verbose_name_plural": "заказы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="код"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="описание"
                    ),
                ),
                (
                    "discount_percent",
                    models.PositiveIntegerField(default=0, verbose_name="скидка %"),
                ),
                (
                    "discount_amount_rub",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="скидка ₽",
                    ),
                ),
                (
                    "discount_amount_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="скидка $",
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True, null=True, verbose_name="действует до"
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        default=0, verbose_name="макс. использований"
                    ),
                ),
                (
                    "used_count",
                    models.PositiveIntegerField(default=0, verbose_name="использовано"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активен"),
                ),
            ],
            options={
                "verbose_name": "промокод",
                "verbose_name_plural": "промокоды",
                "indexes": [
                    models.Index(
                        fields=["code", "is_active"], name="orders_prom_code_e1523f_idx"
                    ),
                    models.Index(
                        fields=["is_active", "valid_until"],
                        name="orders_prom_is_acti_4ce6b4_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrderService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="название")),
                ("image", models.URLField(blank=True, verbose_name="фото")),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="количество"),
                ),
                (
                    "price_rub",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="цена (руб)"
                    ),
                ),
                (
                    "price_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="цена (USD)",
                    ),
                ),
                (
                    "total_rub",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="итого (руб)"
                    ),
                ),
                (
                    "total_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="итого (USD)",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="orders.order",
                        verbose_name="заказ",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.service",
                        verbose_name="услуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "услуга в заказе",
                "verbose_name_plural": "услуги в заказе",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="трек-номер"
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="название")),
                (
                    "sku",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="артикул"
                    ),
                ),
                (
                    "size_value_ru",
                    models.CharField(blank=True, max_length=100, verbose_name="размер"),
                ),
                (
                    "selected_spec_ids",
                    models.JSONField(
                        blank=True, default=list, verbose_name="ID характеристик"
                    ),
                ),
                (
                    "selected_specs_snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Данные характеристик"
                    ),
                ),
                ("image", models.URLField(blank=True, verbose_name="фото")),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="количество"),
                ),
                (
                    "price_rub",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="цена (руб)"
                    ),
                ),
                (
                    "price_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="цена (USD)",
                    ),
                ),
                (
                    "total_rub",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="итого (руб)"
                    ),
                ),
                (
                    "total_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="итого (USD)",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.item",
                        verbose_name="товар",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "товар в заказе",
                "verbose_name_plural": "товары в заказе",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="promo_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orders.promocode",
                verbose_name="промокод",
            ),
        ),
    ]
